### PR TITLE
0.4.3 Use json_reformat instead of python -m json.tool

### PR DESCRIPTION
**Pull request by evuez**

### CODE REVIEW

**Comment by nodesocket** [comment]
The problem is that `json_reformat` does not seem to be nearly as portable. For example OS X and CentOS do not have it installed by default.

How do you even install `json_reformat`on OS X? Brew?

**Comment by evuez** [comment]
It's ANSI C so it's definitely portable ;)
From the [homepage](http://lloyd.github.io/yajl/):

> It's all ANSI C. It's been successfully compiled on debian linux, OSX 10.4 i386 & ppc, OSX 10.5 i386, winXP, FreeBSD 4.10, FreeBSD 6.1 amd64, FreeBSD 7 i386, and windows vista. More platforms and binaries as time permits. 

On OS X it seems like you can use brew: http://brewformulas.org/Yajl

It might not be installed by default on many distributions, but if you want performances and portability this looks like a good option.

**Comment by josegonzalez** [comment]
Note: I added this (with a fallback to `json.tool`) to #9, seems to give a 3x speed boost in the stress test.

**Comment by josegonzalez** [comment]
This can be closed since #9 was merged.

**Comment by nodesocket** [comment]
Refactored and released version `0.6.0`. Now supports `json_reformat` and `jq`.

**Pull request closed without merging**
